application: dreamcachebackend
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api.*
  script: com.dreamiam.rest_api.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^test/.* 
